name：build
on:[push， pull_request]
jobs:
  build:
    runs-on：$ matrix.os
      strategy:
       fail-fast:false
        matrix
        S[windows-latest]
        build_type:[Release]
         enable_ui： [on]
          include：
               ：windows-latest
            build_type: Release
            enable_ui:on
      steps：
         uses：actions/checkout@v3
        with：
           submodules: recursive
         name：ccache
        uses：hendrikmuhs/ccache-action@v1
       if:runner.os ==Linux
         with：
        key：$ft matrix.os 7-$ matrix.enable_ui 
         uses：seanmiddleditch/gha-setup-ninja@masteruses：ilammy/msvc-dev-cmd@v1
      if:runner.os   Windows
        nameInstall Dependencies
        shell： bash
       run：
        if [ “Sf runner.os”==“Linux”]]；thensudo apt-get update -qq
          sudo apt-get install-y
            libx11-dev libxcursor-dev libxi-dev
         name：Generating Makefiles
        shell:bash
        run：
          if [ $f runner.os ==“Windows]]then
    export enable_ccache=off
  else
    export enable_ccache=on
  fi
  curl -L https://github.com/blueloveTH/aseprite/releases/dounload/ve.1/skia.zip --output skia.zip7xskia.zip
  cmake -S-B build -G Ninja 
    DCMAKE_BUILD_TYPE= matrix.build_type 7V
     DENABLE_UI=matrix.enable_ui
     -DENABLE_CCACHE=enable_ccache
    -DLAF_BACKEND=skia
     -DSKIA DIR=./skia
    -DSKIA_LIBRARY_DIR=./skia/out/Release-x64
    -DSKIA_LIBRARY=./skia/out/Release-x64/skia.1ib
name：Compiling
shell:bash
run：
  cd build && ninja
uses:actions/upload-artifact@v3
with：
  name：aseprite
  path
   D:/a/aseprite/aseprite/build/bin/data
    D:/a/aseprite/aseprite/build/bin/aseprite.exe
